services:
  fimbox:
    platform: linux/amd64
    image: cuahsi/handfim:latest
    build:
      context: handfim/
      dockerfile: Dockerfile
    working_dir: /home
    volumes:
      - "${FIMBOX_INPUT_DIR:-../input}:/home/data/inputs"
      - "${FIMBOX_OUTPUT_DIR:-../output}:/home/output"
    ulimits:
      stack: 67108864
